### ISSUE TITLE
T2 Servers Causing Bad Timeouts

### ISSUE THREAD

**Issue by truell20** [HaliteChallenge/Halite#119]
T2 Servers work on CPU credits, so our cpu gets throttled periodically. We use wall time, so this results in timeouts ([even of the example bot](https://halite.io/game.php?replay=ar1478228473-3810014455.hlt)).

To fix the problem, we could increase the timeout, switch to clock time, or switch to the lowest model m3 server.

**Comment by awesomescot** [comment]
Are these servers for running the games in the background?  And the timeouts are the games ending because we think we've given the players the allotted time, but actually our cpu has been throttled and they haven't had much time?

**Comment by awesomescot** [comment]
I think it would be a great idea to move to user time.  I'm not exactly sure how we are launching the subprocesses, but we might be able to measure how much time that process is spending on the cpu.  Like grabbing the time from linux, or top where it shows time per process.  This command will grab the time for a PID, if we have that.  

ps -p [PID] -S -o time

I'm hoping that when we're throttled it would be reflected here and not add more time.

**Comment by truell20** [comment]
> Are these servers for running the games in the background? And the timeouts are the games ending because we think we've given the players the allotted time, but actually our cpu has been throttled and they haven't had much time?

Yes

**Comment by truell20** [comment]
> I think it would be a great idea to move to user time. I'm not exactly sure how we are launching the subprocesses, but we might be able to measure how much time that process is spending on the cpu. Like grabbing the time from linux, or top where it shows time per process. This command will grab the time for a PID, if we have that.

There are a couple of problems with switching to user time. It makes it hard for bots to keep track of how much time they have left to respond. It also requires applying changes to the environment, which *needs* to be stable.

**Comment by awesomescot** [comment]
Ok.  Then it sounds like moving to an m3 might be the easiest solution if the cost isn't a big concern.

**Comment by truell20** [comment]
It would be around a 2.5x increase in cost. Games would run faster so we could open less servers.

**Comment by truell20** [comment]
@Sydriax has proposed we switch just switch to clock time. He says that C++ has support for it.

**Comment by truell20** [comment]
Scratch that. There are problems with clock time. People can stall and use a bunch of wall time without using much cpu. Also its hard for bots to keep track of timeouts.

We are just going to switch to m3 servers.
