### ISSUE TITLE
Missing console output

### ISSUE THREAD

**Issue by SvenPetroll** [HaliteChallenge/Halite#157]
According to the [documentation](https://halite.io/advanced_command_line.php), we are supposed to get some stats like `rank playerid territoryValue strengthValue productionValue stillMovePercentage averageLatency`..

However, after I run a game I get only the rank and id:

```
python3 MyBot.py
python3 RandomBot.py
1478727282-107566369.hlt 107566369
1 2
2 1
 ```

I'm using the latest Ubuntu.

**Comment by truell20** [comment]
We forgot to update the documentation! We took those stats out.
