### ISSUE TITLE
Issues with messages being ignored, etc in current master

### ISSUE THREAD

**Issue by chmullig** [HaliteChallenge/Halite#19]
Hey guys,

FYI, the current master branch has some serious issues that were causing me to tear my hair out this weekend. Messages are received inconsistently, even with -t enabled. (On an ubuntu machine). Just warning you so you make sure to QC it thoroughly before releasing.

Best,
Chris

**Comment by truell20** [comment]
@chmullig Could you elaborate on the issues you were having?

**Comment by chmullig** [comment]
My bot would join the game. Receive the initial line. Then it would make a move. Then it would receive the board from the game, and it wouldn't have changed. However, in the replay the move does happen on the first frame.

**Comment by Sydriax** [comment]
@chmullig 
To me, it sounds like your bot may be confusing the initialization phase with the frame phase. It is correct for your bot to receive two copies of the first frame. The first time is the initialization phase and you should just respond with your bot's name. The second time, your bot should start responding with moves.
The detailed specification for the networking protocol is [here](http://halite.io/website/networking_spec.php). In essence, however, it sounds like you aren't calling getInit or sendInit (or both) and are entering your main game loop too soon.
If I'm misinterpreting your problem, please respond saying so and we'll certainly look into it and find the problem ASAP, as that would be a fairly major bug.

**Comment by chmullig** [comment]
Yeah, I noticed and fixed that. It was that the third line sent didn't reflect my changes after the first line. This was with -t.

**Comment by Sydriax** [comment]
@chmullig 
To be clear, is it that this **only** happens with -t enabled, or is this an issue regardless of the flags?

**Comment by Sydriax** [comment]
@chmullig 
I'm running games on a 4x4 map with the -t flag and bots that output the strings they're sent to a file. I'm using the environment presently up on the website and running on Ubuntu 14.04. The logs I'm getting show different first and second frames received.
In your most recent post, you said, 
> Yeah, I noticed and fixed that. It was that the third line sent didn't reflect my changes after the first line. This was with -t.
You shouldn't be sending moves until after the second map received - the first map sent is purely for initialization purposes and moves received after the first map **will not** register. No game map changes will take place between receiving the first and second map for your bot.

**Comment by truell20** [comment]
Hi @chmullig,

Would you mind sending the source for your modded version of the environment?

**Comment by truell20** [comment]
Since @chmullig said that there seemed to be no issues with the environment on halite.io, I am going to close this.
