### ISSUE TITLE
Tile ownership documentation

### ISSUE THREAD

**Issue by Skuzzzy** [HaliteChallenge/Halite#199]
**edit: I misunderstood the documentation, please ignore. I would delete this, but github disallows this**

The documentation for tile ownership encoding seems off. 
0 1 1 0 0 1 2 2 0 would this be the correct encoding for the tile ownership?

Highlights below
https://github.com/HaliteChallenge/Halite/blob/master/website/advanced_writing_sp.php#L79

https://github.com/HaliteChallenge/Halite/blob/master/website/advanced_writing_sp.php#L82

**Comment by truell20** [comment]
Great!
