### ISSUE TITLE
Compile Success but then can't find MyBot

### ISSUE THREAD

**Issue by robertmassaioli** [HaliteChallenge/Halite#217]
See:

<img width="435" alt="screen shot 2016-11-15 at 6 52 12 am" src="https://cloud.githubusercontent.com/assets/149178/20280301/17f3a246-ab00-11e6-98e3-e9862a2a54d1.png">

I am confused as to how my code could compile and then fail with:

    cat ~/Downloads/error.log 
     --- Init ---
    Error: Could not find or load main class MyBot
     --- Bot used 37 milliseconds ---
    -----------------------------------------------------------------------------
     --- Frame #1 ---
    
    ERRORED!
    No response received.

Especially since MyBot.java is certainly present in the Zip file that I submit: 

    $ unzip -l submission-sources.jar
    ... <snip> ...
                0  11-14-16 23:49   com/rmassaioli/halite/stats/
          642  11-14-16 23:49   com/rmassaioli/halite/stats/PlayerStats.java
          256  11-14-16 23:49   ExpansionBot.java
         2763  11-14-16 23:49   com/rmassaioli/halite/library/GameState.java
         4983  11-14-16 23:49   com/rmassaioli/halite/strategies/ExpansionStrategy.java
          249  11-14-16 23:49   MyBot.java
          244  11-14-16 23:49   OutwardsSprawlBot.java
          114  11-14-16 23:49   com/rmassaioli/halite/library/InitPackage.java
         3507  11-14-16 23:49   com/rmassaioli/halite/strategies/OptimizerStrategy.java
          358  11-14-16 23:49   com/rmassaioli/halite/library/Location.java
         4263  11-14-16 23:49   com/rmassaioli/halite/library/Networking.java
    ... <snip> ...
    $

I think this must be a problem on the server side but I'm not sure what the problem is or how I can fix it.

**Comment by truell20** [comment]
Why are you submitting a jar?

**Comment by truell20** [comment]
The problem does look like it may be on our end. Checked out your post-compile source. There are no class files in it.

**Comment by robertmassaioli** [comment]
The JAR file that I submitted was a sources jar that was built by the maven assembly add-on. Before I submit the JAR I have a test case locally that: 

1. Unzips the source jar.
1. Uses javac to build the source files.
1. Runs an entire game with my bot using the local halite.
1. Verifies that there are no errors.

In short, when I submit my sources inside of the JAR file (which is just a Zip file) then I fully anticipate that it works because it worked for me locally. This has made my rank drop from ~230 to ~440 so it would be great if I could rectify the situation sooner rather than later. I absolutely love this competition btw and am working hard on a more advanced AI.

**Comment by robertmassaioli** [comment]
Oh, and @truell20, I am more than happy to give you access to my source code but I made it a private repo on Bitbucket (because I want it to be private until the competition is over). If you have a bitbucket account though I will happily share the source code with you so that you can debug it more easily! Do you want me to do that?

**Comment by truell20** [comment]
That's fine. We can pull your post-compile source. Will resolve this ASAP.

**Comment by truell20** [comment]
> This has made my rank drop from ~230 to ~440 so it would be great if I could rectify the situation sooner rather than later.

What did you change between your first and last AI. Did you try resubmitting?

**Comment by robertmassaioli** [comment]
The change was to bundle more source files inside of the submitted JAR (zip) file. And I have attempted to resubmit a number of times now to no avail.

**Comment by truell20** [comment]
Ok. Thanks for the info. Will look into it.

**Comment by hyPiRion** [comment]
I had/have a similar problem which I just recently fixed locally: the `javac` command inside the worker uses ASCII encoding instead of UTF-8, which I had locally. Removing any non-ASCII values fixed the issue. I think it should be safe to just tack on `'-encoding', 'UTF-8'` to the javac call from the compiler, so perhaps that should be done.

@robertmassaioli: Could you try to run `javac -encoding ASCII` and see if it produces some errors?

Additionally, I peeked into the source code for the compilation unit, and I notice that there aren't checks to verify that there is a MyBot.class to begin with. Maybe ensuring that there at least is an `out_files=['MyBot.class']` after compiling would be smart.

**Comment by robertmassaioli** [comment]
@hyPiRion nice find! That certainly causes my code to fail to compile successfully:

    ./com/google/common/collect/Multimap.java:34: error: unmappable character for encoding ASCII
     * <li>a ��� 1, 2
             ^
    ./com/google/common/collect/Multimap.java:34: error: unmappable character for encoding ASCII
     * <li>a ��� 1, 2
              ^
    ./com/google/common/collect/Multimap.java:34: error: unmappable character for encoding ASCII
     * <li>a ��� 1, 2
               ^
    ./com/google/common/collect/Multimap.java:35: error: unmappable character for encoding ASCII
     * <li>b ��� 3
             ^
    ./com/google/common/collect/Multimap.java:35: error: unmappable character for encoding ASCII
     * <li>b ��� 3
              ^
    ./com/google/common/collect/Multimap.java:35: error: unmappable character for encoding ASCII
     * <li>b ��� 3
               ^
    ./com/google/common/collect/Multimap.java:41: error: unmappable character for encoding ASCII
     * <li>a ��� 1
             ^
    ./com/google/common/collect/Multimap.java:41: error: unmappable character for encoding ASCII
     * <li>a ��� 1
              ^
    ./com/google/common/collect/Multimap.java:41: error: unmappable character for encoding ASCII
     * <li>a ��� 1
               ^
    ./com/google/common/collect/Multimap.java:42: error: unmappable character for encoding ASCII
     * <li>a ��� 2
             ^
    ./com/google/common/collect/Multimap.java:42: error: unmappable character for encoding ASCII
     * <li>a ��� 2
              ^
    ./com/google/common/collect/Multimap.java:42: error: unmappable character for encoding ASCII
     * <li>a ��� 2
               ^
    ./com/google/common/collect/Multimap.java:43: error: unmappable character for encoding ASCII
     * <li>b ��� 3
             ^
    ./com/google/common/collect/Multimap.java:43: error: unmappable character for encoding ASCII
     * <li>b ��� 3
              ^
    ./com/google/common/collect/Multimap.java:43: error: unmappable character for encoding ASCII
     * <li>b ��� 3
               ^
    ./com/google/common/collect/Range.java:55: error: unmappable character for encoding ASCII
     * <tr><td>{@code (a..+���)} <td>{@code {x | x > a}}      <td>{@link Range#greaterThan greaterThan}
                           ^
    ./com/google/common/collect/Range.java:55: error: unmappable character for encoding ASCII
     * <tr><td>{@code (a..+���)} <td>{@code {x | x > a}}      <td>{@link Range#greaterThan greaterThan}
                            ^
    ./com/google/common/collect/Range.java:55: error: unmappable character for encoding ASCII
     * <tr><td>{@code (a..+���)} <td>{@code {x | x > a}}      <td>{@link Range#greaterThan greaterThan}
                             ^
    ./com/google/common/collect/Range.java:56: error: unmappable character for encoding ASCII
     * <tr><td>{@code [a..+���)} <td>{@code {x | x >= a}}     <td>{@link Range#atLeast atLeast}
                           ^
    ./com/google/common/collect/Range.java:56: error: unmappable character for encoding ASCII
     * <tr><td>{@code [a..+���)} <td>{@code {x | x >= a}}     <td>{@link Range#atLeast atLeast}
                            ^
    ./com/google/common/collect/Range.java:56: error: unmappable character for encoding ASCII
     * <tr><td>{@code [a..+���)} <td>{@code {x | x >= a}}     <td>{@link Range#atLeast atLeast}
                             ^
    ./com/google/common/collect/Range.java:57: error: unmappable character for encoding ASCII
     * <tr><td>{@code (-���..b)} <td>{@code {x | x < b}}      <td>{@link Range#lessThan lessThan}
                        ^
    ./com/google/common/collect/Range.java:57: error: unmappable character for encoding ASCII
     * <tr><td>{@code (-���..b)} <td>{@code {x | x < b}}      <td>{@link Range#lessThan lessThan}
                         ^
    ./com/google/common/collect/Range.java:57: error: unmappable character for encoding ASCII
     * <tr><td>{@code (-���..b)} <td>{@code {x | x < b}}      <td>{@link Range#lessThan lessThan}
                          ^
    ./com/google/common/collect/Range.java:58: error: unmappable character for encoding ASCII
     * <tr><td>{@code (-���..b]} <td>{@code {x | x <= b}}     <td>{@link Range#atMost atMost}
                        ^
    ./com/google/common/collect/Range.java:58: error: unmappable character for encoding ASCII
     * <tr><td>{@code (-���..b]} <td>{@code {x | x <= b}}     <td>{@link Range#atMost atMost}
                         ^
    ./com/google/common/collect/Range.java:58: error: unmappable character for encoding ASCII
     * <tr><td>{@code (-���..b]} <td>{@code {x | x <= b}}     <td>{@link Range#atMost atMost}
                          ^
    ./com/google/common/collect/Range.java:59: error: unmappable character for encoding ASCII
     * <tr><td>{@code (-���..+���)}<td>{@code {x}}              <td>{@link Range#all all}
                        ^
    ./com/google/common/collect/Range.java:59: error: unmappable character for encoding ASCII
     * <tr><td>{@code (-���..+���)}<td>{@code {x}}              <td>{@link Range#all all}
                         ^
    ./com/google/common/collect/Range.java:59: error: unmappable character for encoding ASCII
     * <tr><td>{@code (-���..+���)}<td>{@code {x}}              <td>{@link Range#all all}
                          ^
    ./com/google/common/collect/Range.java:59: error: unmappable character for encoding ASCII
     * <tr><td>{@code (-���..+���)}<td>{@code {x}}              <td>{@link Range#all all}
                              ^
    ./com/google/common/collect/Range.java:59: error: unmappable character for encoding ASCII
     * <tr><td>{@code (-���..+���)}<td>{@code {x}}              <td>{@link Range#all all}
                               ^
    ./com/google/common/collect/Range.java:59: error: unmappable character for encoding ASCII
     * <tr><td>{@code (-���..+���)}<td>{@code {x}}              <td>{@link Range#all all}
                                ^
    ./com/google/common/collect/Range.java:604: error: unmappable character for encoding ASCII
       * <li>[start..+���)
                      ^
    ./com/google/common/collect/Range.java:604: error: unmappable character for encoding ASCII
       * <li>[start..+���)
                       ^
    ./com/google/common/collect/Range.java:604: error: unmappable character for encoding ASCII
       * <li>[start..+���)
                        ^
    ./com/google/common/collect/Range.java:605: error: unmappable character for encoding ASCII
       * <li>(-���..end) (only if type {@code C} is unbounded below)
               ^
    ./com/google/common/collect/Range.java:605: error: unmappable character for encoding ASCII
       * <li>(-���..end) (only if type {@code C} is unbounded below)
                ^
    ./com/google/common/collect/Range.java:605: error: unmappable character for encoding ASCII
       * <li>(-���..end) (only if type {@code C} is unbounded below)
                 ^
    ./com/google/common/collect/Range.java:606: error: unmappable character for encoding ASCII
       * <li>(-���..+���) (only if type {@code C} is unbounded below)
               ^
    ./com/google/common/collect/Range.java:606: error: unmappable character for encoding ASCII
       * <li>(-���..+���) (only if type {@code C} is unbounded below)
                ^
    ./com/google/common/collect/Range.java:606: error: unmappable character for encoding ASCII
       * <li>(-���..+���) (only if type {@code C} is unbounded below)
                 ^
    ./com/google/common/collect/Range.java:606: error: unmappable character for encoding ASCII
       * <li>(-���..+���) (only if type {@code C} is unbounded below)
                     ^
    ./com/google/common/collect/Range.java:606: error: unmappable character for encoding ASCII
       * <li>(-���..+���) (only if type {@code C} is unbounded below)
                      ^
    ./com/google/common/collect/Range.java:606: error: unmappable character for encoding ASCII
       * <li>(-���..+���) (only if type {@code C} is unbounded below)
                       ^
    ./com/google/common/collect/ContiguousSet.java:171: error: unmappable character for encoding ASCII
       * {@code [1..���)}.
                    ^
    ./com/google/common/collect/ContiguousSet.java:171: error: unmappable character for encoding ASCII
       * {@code [1..���)}.
                     ^
    ./com/google/common/collect/ContiguousSet.java:171: error: unmappable character for encoding ASCII
       * {@code [1..���)}.
                      ^
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    48 errors

Maybe we could look into setting incoding UTF-8 by default.

**Comment by hyPiRion** [comment]
I've added a pull request which sets the default encoding to UTF-8 (Backwards compatible with ASCII, the current encoding) and also checks for the existence of MyBot.class.

In the meantime I've resolved this in my bot by just removing the UTF-8 characters from the source code. It's a hassle, but at least it compiles and runs.

**Comment by robertmassaioli** [comment]
This is awesome! Thanks for the fast response! It is much easier for me to just have the source code that I submit compiled with UTF-8 encoding.

**Comment by robertmassaioli** [comment]
P.S. How will I know when I can re-submit my bot and production will have this change?

**Comment by truell20** [comment]
Changes are live.

**Comment by robertmassaioli** [comment]
@truell20 I am still getting MyBot missing errors. :(

**Comment by robertmassaioli** [comment]
This issue still exists but I'm now submitting my code as a JAR file.
