### ISSUE TITLE
Starting position/strength/production should always allow for some growth

### ISSUE THREAD

**Issue by adereth** [HaliteChallenge/Halite#225]
Check out: https://halite.io/game.php?replay=ar1479172186-2629957148.hlt

The pieces start on a 0 production square.  All the adjacent squares that can be captured have 0 production.  All the squares adjacent to those squares have too much starting strength to capture.

**Comment by Sydriax** [comment]
I've now at least partially fixed this problem, as once the newest env build goes live on servers players will be guaranteed to get a production of at least 1 on their starting square.
