### ISSUE TITLE
Unfair starting positions

### ISSUE THREAD

**Issue by truell20** [HaliteChallenge/Halite#246]
Users aren't always equidistant from one another. This puts some players at an immediate advantage, since some players may be closer to weak opponents than others. This adds volatility to the rankings. 

[Here is one example](https://halite.io/game.php?replay=ar1479672367-299694187.hlt). @djma and @erdman were placed right next to one another. They had to fight over the high production mass between them. @revoklaw got to enjoy an uncontested, high production mass because @tarriel was a relatively weak opponent.

**Comment by erdman** [comment]
Is this really a bug?  @erdman's relative position to @djma is same as
@revoklaw to @tarriel, each with high productivity area between them.  The
imbalance from this game is that the bot opposite @revoklaw did not fight
for the high productivity area.  I don't think there's much you can do --
you're always going to have a relatively weaker bot in any given match, and
someone else will benefit from that, and it does cause some volatility in
the rankings, but it seems natural and unavoidable.  Or maybe you're seeing
something else that I'm not?

**Comment by nmalaguti** [comment]
When testing my bots locally, I've found that replaying with the same map with every possible permutation of players usually reveals biased starting positions (the bot in x position is more likely to win), even in 1v1 matches against itself.

At first I was concerned, but over enough games biased starting positions should average out among all competitors. To me, this isn't much different from sometimes playing as white or black in Chess. Any one match is insufficient to make a definitive statement of raking between contestants.

**Comment by erdman** [comment]
I think I found a map that could be considered "unfair".  I was surprised
to find it.  Just thought of this thread -- apologies if this should go
into a new or different thread.  Here is the map and game:
https://halite.io/game.php?replay=ar1480061447-2832866290.hlt

The starting positions are fine -- it's the symmetry that is at issue.
Like every other map, this one looks to be symmetrical at first glance
(click on 'p' to show the production areas).   However, look closely at the
high productivity area that @brianvanleeuwen and @erdman fight over in the
very beginning.  It looks like his side and my side are mirror-reflected
left-to-right, but when you start clicking around the different boxes, it's
easy to find corresponding pairs that "should" have the same strength and
production values, but they are, in fact, different.

For instance, his 7th box is a (53,6).  The corresponding box on my side is
a (52,6).  There are several other examples with larger differences in
magnitude in that higher production area surrounding where our initial
contact takes place.

**Comment by Sydriax** [comment]
Should be resolved; see other thread.
