### ISSUE TITLE
Is this a bug in Halite/environment/core/Halite.cpp ?

### ISSUE THREAD

**Issue by erdman** [HaliteChallenge/Halite#284]
I was looking for something else, but I came across this in lines 197 & 198:

```
full_strength_count[game_map.contents[a][b].owner - 1] += game_map.contents[a][b].strength;
full_production_count[game_map.contents[a][b].owner - 1] += game_map.contents[a][b].strength;
```

I couldn't quite work out what's going on here (don't speak cpp), but it looks like your adding .strength to full_strength_count, and also adding .strength to full_production_count?  I suspect you might want to be adding .production there?

**Comment by truell20** [comment]
@Sydriax has informed me: This is indeed a bug, but on some dead code that is still in the environment that was for calculating various statistics (we will remove the dead code)
