### ISSUE TITLE
Unneeded <br> tags

### ISSUE THREAD

**Issue by truell20** [HaliteChallenge/Halite#285]
http://forums.halite.io/t/unneeded-br-tags-in-visualizer/536/5

**Comment by Janzert** [comment]
Here's a bit more information. The extra tags were added with commit 498882c28e36cc47d514700099e71838078f8979 which added a footer include to that and a bunch of other pages. The actual footer include was then pulled back out with commit 88ab4efc7d68ae4f1ca8c1b2d1e63cd2b50fc2ed but the extra tags got left.

**Comment by truell20** [comment]
Thanks @Janzert. Hadn't looked into it at all yet.
