### ISSUE TITLE
Some maps lack symmetry

### ISSUE THREAD

**Issue by erdman** [HaliteChallenge/Halite#313]
I noted a minor false-symmetry map in another thread (https://github.com/HaliteChallenge/Halite/issues/246#issuecomment-262912300).  The map I referred to there requires quite close examination to reveal it's asymmetry:
https://halite.io/game.php?replay=ar1480061447-2832866290.hlt

However, @AisleCC reported this one, which is more egregious than the one I ran into:
https://halite.io/game.php?replay=ar1481039228-1360914193.hlt

These are the only two incidences that I'm aware of, which is only to say that I think it's fairly uncommon-to-rare for this bug to present itself.

**Comment by Sydriax** [comment]
Yeah, this bug is sufficiently uncommon that we hadn't gotten around to fixing it. I'll take a look at it tomorrow, and if I don't find it then I'll fix it over the weekend for sure.

I've only ever seen 6-player maps be asymmetric -- that will probably be my launching point in searching for the bug.

**Comment by Sydriax** [comment]
Update on progress searching for bug:
Through experimentation, it appears that this bug fairly consistently when two conditions are satisfied:
First, the map must contain six players.
Second, the map must have some sort of shift or mirroring in it (I haven't yet narrowed which is responsible).
Presently trying some larger numbers of players to see if that will do it as well.

**Comment by Sydriax** [comment]
Was able to replicate on 8 player map but not 7. Suspecting that it has something to do with shifting multiple players at once.

**Comment by Sydriax** [comment]
Isolated to be a problem within the shifts.

**Comment by Sydriax** [comment]
Disabled shifts for 6-player maps; should be fixed.
