### ISSUE TITLE
Visualizer not showing much of the players' territory

### ISSUE THREAD

**Issue by pmwhite** [HaliteChallenge/Halite#342]
I downloaded and extracted the python starter bot. Then I executed the linux install script in the same folder. I ran `sh ./runGame.sh` to run the test game. This gave me a .hlt file. I uploaded this file to the visualizer.

The map visualizer does not show very much on the map. Each player appears to have gained  only 1 or 2 squares, and no strength appears to be building on those squares. I copied the image of the game into gimp, applied a background, and attached the image for you to see.

Note that the strength is fluctuation while there are only two squares for each player on the board.
![halite-issue3](https://cloud.githubusercontent.com/assets/11892254/21428768/b3ba83ca-c829-11e6-8236-550bf93e5cbf.png)

I hope that's helpful enough. Should I upload my .hlt file as well?

**Comment by truell20** [comment]
I don't believe that this is a bug.

Random bots are very very bad at playing Halite. First, they move their squares even when they are at zero strength. Second, they will move strength into a map piece even when they cannot take the map piece. Only one fifth of all their moves will be still moves. Halite pieces don't gain strength when they move, so this loses them a lot of production.

**Comment by truell20** [comment]
Does that make sense?
