### ISSUE TITLE
Make code submission instructions clearer

### ISSUE THREAD

**Issue by sahuguet** [HaliteChallenge/Halite#37]
- submit file and not folder
- submit using the correct file name

The info appears in the email message you get with a bot submission error. This is too late and frustrating. It should appear sooner. Create a dedicated page for bot submission.

**Comment by truell20** [comment]
Totally agree. Will add a modal with that info that pops up when you submit the first time.

**Comment by truell20** [comment]
Fixed by 7a4a2be49321e8ad9ae29356318142f8db69c557
