### ISSUE TITLE
Cannot create account

### ISSUE THREAD

**Issue by aseiple678** [HaliteChallenge/Halite#383]
The submit button on https://halite.io/associate.php page does not work when creating an account.

High School list kicks out error:
~~~Uncaught` ReferenceError: getValidHighSchools is not defined
    at HTMLDocument.<anonymous> (associate.js:71)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)
~~~

**Comment by truell20** [comment]
Could you give us your full console output? Also what browser are you using?

**Comment by aseiple678** [comment]
I am using the latest release of chrome. And the jQuery error in the
original post is that console output.

**Comment by aseiple678** [comment]
Registration just worked on Android chrome
