### ISSUE TITLE
Replay screen improvement

### ISSUE THREAD

**Issue by sahuguet** [HaliteChallenge/Halite#39]
- not clear that you can move the timeline back and forth
- bottom chart truncated

URL = http://halite.io/website/game.php?replay=1475691303-670599101.hlt

<img width="764" alt="screen shot 2016-10-05 at 2 35 14 pm" src="https://cloud.githubusercontent.com/assets/355907/19126448/feede7dc-8b08-11e6-8364-e315a3bdafa8.png">

**Comment by truell20** [comment]
fixed graph truncation
help button added
